//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooTeans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int ID_TrabajoRealizado { get; set; }
    
        public virtual TrabajoRealizado TrabajoRealizado { get; set; }
    }
}
