//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooTeans.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TattoTeansEntities : DbContext
    {
        public TattoTeansEntities()
            : base("name=TattoTeansEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaProducto> CategoriaProductoes { get; set; }
        public virtual DbSet<CategoriaTatuaje> CategoriaTatuajes { get; set; }
        public virtual DbSet<CompraDetalle> CompraDetalles { get; set; }
        public virtual DbSet<FacturaCompra> FacturaCompras { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<LocalPorUsuarioPorCategoria> LocalPorUsuarioPorCategorias { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoDePago> TipoDePagoes { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<TrabajoRealizado> TrabajoRealizadoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuarioPorCategoria> UsuarioPorCategorias { get; set; }
    }
}
