//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosUPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Eventos_TPEntitiesContext : DbContext
    {
        public Eventos_TPEntitiesContext()
            : base("name=Eventos_TPEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividads { get; set; }
        public virtual DbSet<Equipo> Equipoes { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Evento_Actividad> Evento_Actividad { get; set; }
        public virtual DbSet<Evento_Equipo> Evento_Equipo { get; set; }
        public virtual DbSet<Evento_Material> Evento_Material { get; set; }
        public virtual DbSet<Evento_Personal> Evento_Personal { get; set; }
        public virtual DbSet<Evento_Servicio> Evento_Servicio { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
