//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosUPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Material
    {
        public int id_evento_material { get; set; }
        public int id_evento { get; set; }
        public int id_material { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Material Material { get; set; }
    }
}
